name: Ecommerce Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Creating Docker Image
        run: docker build -t amank736836/mern-ecommerce-frontend-2024:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      

      - name: Pushing Docker Image to Docker Hub
        run: |
          docker push amank736836/mern-ecommerce-frontend-2024:latest
          docker logout

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH login and Deploy
        run: |
          sudo apt-get update -y
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-52-54-104-85.compute-1.amazonaws.com
          sudo docker pull amank736836/mern-ecommerce-frontend-2024:latest &&
          cd app &&
          sudo docker-compose down &&
          sudo docker-compose up -d &&
          exit
