name: Ecommerce Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Creating Docker Image
        run: docker build -t amank736836/mern-ecommerce-frontend-2024:latest .

      - name: Pushing Docker Image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push amank736836/mern-ecommerce-frontend-2024:latest
          docker logout

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH login and Deploy
        run: |
          sudo apt-get update -y
          ssh -o StrictHostKeyChecking=no ubuntu@52.54.104.85 << 'EOF'
          echo "Connected to the server!"
          sudo docker pull amank736836/mern-ecommerce-frontend-2024:latest &&
          cd /app &&
          sudo docker-compose down &&
          sudo docker-compose up -d &&
          exit
          '
